{% set name = "google-cloud-dataplex" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-cloud-dataplex-{{ version }}.tar.gz
  sha256: f66429939dfcd07c576fa5535edaa1190dd86f9461d37b5a6d91909ad68c987d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - proto-plus >=1.15.0

test:
  imports:
    - google.cloud.dataplex
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-dataplex
  summary: Dataplex API client library
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
